import Head from 'next/head'
import ListItem from '@/common/components/listItem'
import ListContainer from '@/common/components/listOfItems'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const testListItems = ["School Work Tasks", "Work Tasks", "Personal Projects"]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListContainer >
        {testListItems.map(title => {
          return <ListItem title={title} />
        })}
      </ListContainer>
    </>
  )
}
