import Head from 'next/head'
import Link from 'next/link'
import ListItem from '@/common/components/listItem'
import ListContainer from '@/common/components/listOfItems'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const testListItems = [{title: "School Work Tasks", id: 1}, {title: "Work Tasks", id: 2}, {title: "Personal Projects", id:3}]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListContainer >
        {testListItems.map(list => {
          return (<Link href={{
            pathname: '/list/[id]',
            query: {id: list.id},
          }}>
          <ListItem title={list.title} />
          </Link>);
        })}
      </ListContainer>
    </>
  )
}
